# Makefile
# 
# Objetivo: Compilar e o exemplo de uso de assets em C.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves 16/07/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	exemplo.x

exemplo.x:	exemplo.c
	gcc exemplo.c -o exemplo.x

clean:
	rm *.x
help:
	@echo "Para compilar o exemplo utilize o comando 'make'"
