# Makefile
# 
# Objetivo: Compilação do daemon gb_daemon.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo Dirack 28/10/2019
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all: 
	gcc daemon.c gb_daemon.c -o gb_daemon

clean:
	rm gb_daemon

help:
	@echo "Para compilar o gb_daemon basta rodar o comando 'make'"
