# Makefile
# 
# Objetivo: Exemplo de estrutra de dados pilha de ints em C.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves 13/07/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	pilha.x
	./pilha.x

pilha.x:	pilha.c
	gcc $^ -o $@ -g

clean:
	rm *.x

help:
	@echo "Exemplo pilha de ints em C"
	@echo "Para compilar e executar use 'make'"
