# Makefile
# 
# Objetivo: Compilar o programa main.c para o GDB.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 08/08/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.


all: main.x

main.x:	main.c
	@echo "Compilar main.c com a lista de símbolos para o GBD..."
	gcc -g main.c -o main.x

clean:
	rm *.x

help:
	@echo "Compilar o exemplo com 'make'"
