# Makefile
# 
# Objetivo: Compilar o exemplo de uso com a lista de símbolos para o GDB.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 03/09/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all: main.x

main.x:	main.c
	gcc -g $< -o $@

clean:
	rm *.x

help:
	@echo "Para compilar o exemplo de uso basta utilizar 'make'"
