# Makefile
# 
# Objetivo: Compilar o exemplo da fila já com a lista de símbolos do GDB.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves (Dirack) 09/09/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	fila.x

fila.x:	fila.c
	gcc fila.c -o fila.x -g

clean:
	rm *.x

help:
	@echo "Para compilar o exemplo já com a lista de símbolos do GDB utilize 'make'"

