# Makefile
# 
# Objetivo: Compilar e rodar o exemplo de uso do pré processamento em C.
# 
# Site: https://dirack.github.io
# 
# Versão 1.0
# 
# Programador: Rodolfo A C Neves 15/07/2021
# 
# Email: rodolfo_profissional@hotmail.com
# 
# Licença: GPL-3.0 <https://www.gnu.org/licenses/gpl-3.0.txt>.

all:	teste.c _maisum.h _bool.h
	gcc -E teste.c
